2024-09-02 16:56:24 dotfiles updates
Former-commit-id: f52a66b1ed4c1b261f0e5fb1b521d4ba8ff369b1
Former-commit-id: ab7718fc7be31740ec5f1106a5752b14b300fd6f
Former-commit-id: 5049672c0fe5935adce8cda55bacf84b45f03391
Former-commit-id: 9523af7d88b77f8682e6e0a8669914704260e58f
Former-commit-id: 3714c7c54b0778308c06a42c6d1fa5fe982afb13
Former-commit-id: 3fd9b6c66a474bef4d64e32a2cdd6b673a3bbcb9
Former-commit-id: 494b940f2ca2b384df7dfbe46d894332d881ab44

diff --git a/.local/bin/devsh b/.local/bin/devsh
--- a/.local/bin/devsh
+++ b/.local/bin/devsh
@@ -32,23 +32,47 @@ log() {
 check_docker() {
 	log "INFO" "Checking if Docker is installed..."
 	log "INFO" "Evaluating: 'command -v docker'"
+
 	if ! command -v docker &>/dev/null; then
 		log "ERROR" "Docker is required to start the development environment. Please install Docker and try again."
-		exit 1
-	fi
-	log "INFO" "Docker is installed."
+    return 1
+  fi
+
+  exists="Docker"
+	log "INFO" "${exists} is installed."
 }
 
-run_docker_command() {
-	local cmd="docker run --rm -it ${@} psadi/pde:latest"
+check_podman() {
+
+	log "INFO" "Checking if Podman is installed..."
+	log "INFO" "Evaluating: 'command -v podman'"
+  if ! command -v podman &>/dev/null; then
+		log "ERROR" "Podman is required to start the development environment. Please install Podman and try again."
+    return 1
+	fi
+  
+  exists="Podman"
+	log "INFO" "${exists} is installed."
+}
+
+run_command() {
+  case $exists in 
+    'Docker')
+	    local cmd="docker run --rm -it ${@} psadi/pde:latest"
+      ;;
+    'Podman')
+	    local cmd="podman run --rm -it ${@} docker.io/psadi/pde:latest"
+      ;;
+    esac
+
 	log "INFO" "Executing: '${cmd}'"
 	eval "${cmd}"
 	exit $?
 }
 
 main() {
-	check_docker
-	run_docker_command "${@}"
+	check_docker || check_podman || exit 1
+	run_command "${@}"
 }
 
 main "${@}"
